import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import '../globals.css';
import { Inter } from 'next/font/google';
import { GTMInitialize } from '@grace-studio/graceful-next/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '@grace-studio/graceful-next',
  description: 'Generated by create next app',
};

const Layout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) => {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en">
      <GTMInitialize id={process.env.NEXT_PUBLIC_GTM_ID} />
      <body className={inter.className}>
        <NextIntlClientProvider messages={null}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default Layout;
